/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PersonIdImport } from './routes/person/$id'

// Create Virtual Routes

const FormLazyImport = createFileRoute('/form')()
const CurrencyLazyImport = createFileRoute('/currency')()
const IndexLazyImport = createFileRoute('/')()
const PersonIndexLazyImport = createFileRoute('/person/')()

// Create/Update Routes

const FormLazyRoute = FormLazyImport.update({
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const CurrencyLazyRoute = CurrencyLazyImport.update({
  path: '/currency',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/currency.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PersonIndexLazyRoute = PersonIndexLazyImport.update({
  path: '/person/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/person/index.lazy').then((d) => d.Route))

const PersonIdRoute = PersonIdImport.update({
  path: '/person/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyLazyImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdImport
      parentRoute: typeof rootRoute
    }
    '/person/': {
      id: '/person/'
      path: '/person'
      fullPath: '/person'
      preLoaderRoute: typeof PersonIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CurrencyLazyRoute,
  FormLazyRoute,
  PersonIdRoute,
  PersonIndexLazyRoute,
})

/* prettier-ignore-end */


/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/currency",
        "/form",
        "/person/$id",
        "/person/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/currency": {
      "filePath": "currency.lazy.tsx"
    },
    "/form": {
      "filePath": "form.lazy.tsx"
    },
    "/person/$id": {
      "filePath": "person/$id.tsx"
    },
    "/person/": {
      "filePath": "person/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */